package com.ccms.service;

import com.ccms.entity.expense.ExpenseReimburse;
import com.ccms.repository.expense.ExpenseReimburseRepository;
import com.ccms.service.impl.ExpenseReimburseServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * 费用报销服务测试类
 */
class ExpenseReimburseServiceTest {

    @Mock
    private ExpenseReimburseRepository expenseReimburseRepository;

    @InjectMocks
    private ExpenseReimburseServiceImpl expenseReimburseService;

    private ExpenseReimburse testReimburse;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        
        testReimburse = new ExpenseReimburse();
        testReimburse.setId(1L);
        testReimburse.setReimburseNo("REIMBURSE_001");
        testReimburse.setTitle("测试报销");
        testReimburse.setApplyUserId(1001L);
        testReimburse.setApplyUserName("测试用户");
        testReimburse.setDeptId(1L);
        testReimburse.setDeptName("测试部门");
        testReimburse.setReimburseDate(LocalDate.now());
        testReimburse.setTotalAmount(new BigDecimal("1000.00"));
        testReimburse.setStatus(0);
        testReimburse.setApprovalStatus(0);
    }

    @Test
    void testCreateExpenseReimburse_Success() {
        when(expenseReimburseRepository.save(any(ExpenseReimburse.class))).thenReturn(testReimburse);
        
        ExpenseReimburse created = expenseReimburseService.createExpenseReimburse(testReimburse);
        
        assertNotNull(created);
        assertEquals("REIMBURSE_001", created.getReimburseNo());
        assertEquals(0, created.getStatus());
        assertEquals(0, created.getApprovalStatus());
        assertEquals(0, created.getPaymentStatus());
        
        verify(expenseReimburseRepository, times(1)).save(any(ExpenseReimburse.class));
    }

    @Test
    void testCreateExpenseReimburse_WithAutoGeneratedNumber() {
        testReimburse.setReimburseNo(null);
        when(expenseReimburseRepository.save(any(ExpenseReimburse.class))).thenReturn(testReimburse);
        
        ExpenseReimburse created = expenseReimburseService.createExpenseReimburse(testReimburse);
        
        assertNotNull(created.getReimburseNo());
        assertTrue(created.getReimburseNo().startsWith("REIMBURSE_"));
    }

    @Test
    void testGetExpenseReimburseById_Success() {
        when(expenseReimburseRepository.findById(1L)).thenReturn(java.util.Optional.of(testReimburse));
        
        ExpenseReimburse found = expenseReimburseService.getExpenseReimburseById(1L);
        
        assertNotNull(found);
        assertEquals(1L, found.getId());
        assertEquals("REIMBURSE_001", found.getReimburseNo());
    }

    @Test
    void testGetExpenseReimburseById_NotFound() {
        when(expenseReimburseRepository.findById(999L)).thenReturn(java.util.Optional.empty());
        
        ExpenseReimburse found = expenseReimburseService.getExpenseReimburseById(999L);
        
        assertNull(found);
    }

    @Test
    void testUpdateExpenseReimburse_Success() {
        ExpenseReimburse existingReimburse = new ExpenseReimburse();
        existingReimburse.setId(1L);
        existingReimburse.setStatus(0);
        existingReimburse.setApprovalStatus(0);
        existingReimburse.setTitle("原标题");
        
        when(expenseReimburseRepository.findById(1L)).thenReturn(Optional.of(existingReimburse));
        when(expenseReimburseRepository.save(any(ExpenseReimburse.class))).thenReturn(testReimburse);
        
        testReimburse.setTitle("新标题");
        ExpenseReimburse updated = expenseReimburseService.updateExpenseReimburse(testReimburse);
        
        assertNotNull(updated);
        assertEquals("新标题", updated.getTitle());
        verify(expenseReimburseRepository, times(1)).save(any(ExpenseReimburse.class));
    }

    @Test
    void testUpdateExpenseReimburse_NotFound() {
        when(expenseReimburseRepository.findById(999L)).thenReturn(Optional.empty());
        
        testReimburse.setId(999L);
        
        Exception exception = assertThrows(RuntimeException.class, () -> {
            expenseReimburseService.updateExpenseReimburse(testReimburse);
        });
        
        assertEquals("费用报销申请不存在", exception.getMessage());
    }

    @Test
    void testUpdateExpenseReimburse_InvalidStatus() {
        ExpenseReimburse existingReimburse = new ExpenseReimburse();
        existingReimburse.setId(1L);
        existingReimburse.setStatus(1); // 非草稿状态
        existingReimburse.setApprovalStatus(1);
        
        when(expenseReimburseRepository.findById(1L)).thenReturn(Optional.of(existingReimburse));
        
        testReimburse.setId(1L);
        
        Exception exception = assertThrows(RuntimeException.class, () -> {
            expenseReimburseService.updateExpenseReimburse(testReimburse);
        });
        
        assertEquals("非草稿状态的费用报销申请不允许修改", exception.getMessage());
    }

    @Test
    void testSubmitExpenseReimburseForApproval_Success() {
        testReimburse.setStatus(0);
        testReimburse.setApprovalStatus(0);
        
        when(expenseReimburseRepository.findById(1L)).thenReturn(Optional.of(testReimburse));
        when(expenseReimburseRepository.save(any(ExpenseReimburse.class))).thenReturn(testReimburse);
        
        expenseReimburseService.submitExpenseReimburseForApproval(1L);
        
        assertEquals(1, testReimburse.getStatus());
        assertEquals(1, testReimburse.getApprovalStatus());
        assertNotNull(testReimburse.getSubmitTime());
        
        verify(expenseReimburseRepository, times(1)).save(testReimburse);
    }

    @Test
    void testSubmitExpenseReimburseForApproval_NotFound() {
        when(expenseReimburseRepository.findById(999L)).thenReturn(Optional.empty());
        
        Exception exception = assertThrows(RuntimeException.class, () -> {
            expenseReimburseService.submitExpenseReimburseForApproval(999L);
        });
        
        assertEquals("费用报销申请不存在", exception.getMessage());
    }

    @Test
    void testApproveExpenseReimburse_Success() {
        ExpenseReimburse existingReimburse = new ExpenseReimburse();
        existingReimburse.setId(1L);
        existingReimburse.setApprovalStatus(1); // 审批中状态
        
        when(expenseReimburseRepository.findById(1L)).thenReturn(Optional.of(existingReimburse));
        when(expenseReimburseRepository.save(any(ExpenseReimburse.class))).thenReturn(existingReimburse);
        
        boolean result = expenseReimburseService.approveExpenseReimburse(1L, 1001L, 1, "审批通过");
        
        assertTrue(result);
        assertEquals(2, existingReimburse.getApprovalStatus()); // 已审批
        assertEquals(2, existingReimburse.getStatus()); // 审批通过
        assertEquals(1001L, existingReimburse.getApprovedUserId());
        assertNotNull(existingReimburse.getApprovedTime());
        assertEquals("审批通过", existingReimburse.getApprovalComment());
    }

    @Test
    void testApproveExpenseReimburse_Reject() {
        ExpenseReimburse existingReimburse = new ExpenseReimburse();
        existingReimburse.setId(1L);
        existingReimburse.setApprovalStatus(1);
        
        when(expenseReimburseRepository.findById(1L)).thenReturn(Optional.of(existingReimburse));
        when(expenseReimburseRepository.save(any(ExpenseReimburse.class))).thenReturn(existingReimburse);
        
        boolean result = expenseReimburseService.approveExpenseReimburse(1L, 1001L, 2, "审批拒绝");
        
        assertTrue(result);
        assertEquals(3, existingReimburse.getApprovalStatus()); // 已拒绝
        assertEquals(3, existingReimburse.getStatus()); // 审批拒绝
        assertEquals("审批拒绝", existingReimburse.getApprovalComment());
    }

    @Test
    void testDeleteExpenseReimburse_Success() {
        when(expenseReimburseRepository.deleteById(1L)).thenReturn(true);
        
        boolean result = expenseReimburseService.deleteExpenseReimburse(1L);
        
        assertTrue(result);
        verify(expenseReimburseRepository, times(1)).deleteById(1L);
    }

    @Test
    void testDeleteExpenseReimburse_Failure() {
        when(expenseReimburseRepository.deleteById(1L)).thenThrow(new RuntimeException("删除失败"));
        
        boolean result = expenseReimburseService.deleteExpenseReimburse(1L);
        
        assertFalse(result);
    }

    @Test
    void testProcessPayment_Success() {
        ExpenseReimburse existingReimburse = new ExpenseReimburse();
        existingReimburse.setId(1L);
        existingReimburse.setApprovalStatus(2); // 已审批
        existingReimburse.setPaymentStatus(0); // 未支付
        existingReimburse.setTotalAmount(new BigDecimal("1000.00"));
        
        when(expenseReimburseRepository.findById(1L)).thenReturn(Optional.of(existingReimburse));
        when(expenseReimburseRepository.save(any(ExpenseReimburse.class))).thenReturn(existingReimburse);
        
        boolean result = expenseReimburseService.processPayment(1L, 2001L, "现金", "PAY001");
        
        assertTrue(result);
        assertEquals(1, existingReimburse.getPaymentStatus()); // 已支付
        assertNotNull(existingReimburse.getPaymentTime());
    }

    @Test
    void testCheckPermission_AlwaysTrue() {
        boolean result = expenseReimburseService.checkPermission("token123", "expense-reimburse:view");
        
        assertTrue(result);
    }
}