/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ApprovalActions: typeof import('./components/approval/ApprovalActions.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ChartDisplay: typeof import('./components/common/ChartDisplay.vue')['default']
    CustomDrawer: typeof import('./components/common/CustomDrawer.vue')['default']
    CustomForm: typeof import('./components/common/CustomForm.vue')['default']
    CustomModal: typeof import('./components/common/CustomModal.vue')['default']
    DataExport: typeof import('./components/common/DataExport.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FileUpload: typeof import('./components/common/FileUpload.vue')['default']
    InvoiceUpload: typeof import('./components/reimburse/InvoiceUpload.vue')['default']
    Message: typeof import('./components/common/Message.vue')['default']
    PermissionButton: typeof import('./components/permission/PermissionButton.vue')['default']
    PermissionContainer: typeof import('./components/permission/PermissionContainer.vue')['default']
    PermissionMenu: typeof import('./components/permission/PermissionMenu.vue')['default']
    PermissionMenuItem: typeof import('./components/permission/PermissionMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
